name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bundling Golang for Linux
        run: GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build -o price-bot .
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: archangelx360/price-bot/bot
          tag_with_ref: true
          tag_with_sha: true
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying on ${{ secrets.HOST }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            docker stop price-bot || true
            docker rm price-bot || true
            docker login -u ${{ github.actor }} -p ${{ github.token }} docker.pkg.github.com
            docker pull docker.pkg.github.com/archangelx360/price-bot/bot:latest
            docker run -d -v /opt/price-bot/config:/opt/config --name=price-bot docker.pkg.github.com/archangelx360/price-bot/bot:latest
